[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "emsarray"
version = "1.0.0a1"
description = "xarray extension that supports multiple geometry conventions"
authors = [
	{name = "Coastal Environmental Modelling team, Oceans and Atmosphere, CSIRO", email = "coasts@csiro.au"},
]
readme = "README.md"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
	"bottleneck >=1.3",
	"geojson >=3.1",
	"netcdf4 >=1.6.4",
	"numpy >=1.25",
	"packaging >=23.2",
	"shapely >=2.0",
	"pyshp >=2.3",
	"xarray[parallel] >=2024.1",
]

dynamic = ["readme"]

[project.urls]
Documentation = "https://emsarray.readthedocs.io/"
"Release notes" = "https://emsarray.readthedocs.io/en/stable/releases/1.0.0a1/"
Source = "https://github.com/csiro-coasts/emsarray/"

[tool.poetry.dependencies]
cartopy = { version = ">=0.22", optional = true }
matplotlib = { version = ">=3.8", optional = true }
pykdtree = { version = ">=1.3", optional = true }
cfunits = { version = ">= 3.3", optional = true }
pooch = { version = ">=1.8", optional = true }

[project.optional-dependencies]
plot = [
	"cartopy",
	"matplotlib",
	"pykdtree",
	"cfunits",
]

tutorial = [
	"pooch",
]

# This should be the union of all optional dependencies.
# pip allows you to do "emsarray[plot,tutorial]" but poetry does not.
complete = [
	"cartopy",
	"matplotlib",
	"pykdtree",
	"cfunits",
	"pooch",
]

[dependency-groups]
docs = [
	"sphinx ~=8.2.3",
	"sphinx_book_theme ~=1.1.4",
	"sphinxcontrib-video ~=0.4.1",
	"sphinx-gallery ~=0.20.0",
	"livereload~=2.7.1",
]

testing = [
	"pytest",
	"pytest-cov",
	"pytest-mpl",
	"mypy",
	"pandas-stubs",
	"types-pytz",
	"flake8",
	"isort",
	"freezegun",
]

[tool.poetry.group.docs]
optional = true

[project.scripts]
emsarray = "emsarray.cli:main"

[project.entry-points."emsarray.conventions"]
ArakawaC = "emsarray.conventions.arakawa_c:ArakawaC"
CFGrid1D = "emsarray.conventions.grid:CFGrid1D"
CFGrid2D = "emsarray.conventions.grid:CFGrid2D"
ShocSimple = "emsarray.conventions.shoc:ShocSimple"
ShocStandard = "emsarray.conventions.shoc:ShocStandard"
UGrid = "emsarray.conventions.ugrid:UGrid"
# emsarray.conventions end - marker used by docs

[tool.poetry]

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
	"error",
]
markers = [
	"matplotlib: Tests that involve matplotlib and plotting",
	"tutorial: Tests that involve the tutorial datasets",
	"memory_usage: Regression tests for memory allocations",
]

mpl-use-full-test-name = true
mpl-baseline-path = "tests/baseline_images"
mpl-default-style = "default"

[tool.mypy]
python_version = "3.12"

disallow_untyped_defs = true
warn_return_any = true
warn_unused_configs = true

mypy_path = "$MYPY_CONFIG_FILE_DIR/src"

[[tool.mypy.overrides]]
# These modules do not (yet) have type stubs, so they need to be explicitly ignored
module = [
	"cartopy.*",
	"cftime.*",
	"cfunits.*",
	"cryptography.*",
	"geojson.*",
	"matplotlib.*",
	"netCDF4.*",
	"pooch.*",
	"pytest.*",
	"shapefile.*",
	"shapely.*",
	"traitlets.*",
]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false
warn_return_any = false

[tool.isort]
multi_line_output = 5
known_first_party = "emsarray,tests"

[tool.coverage.run]
source_pkgs = ["emsarray"]

[tool.coverage.report]
exclude_lines = [
	"# pragma: no cover",
	"@abc\\.abstract",
	"if TYPE_CHECKING:",
]
