name: Set up environment
description: Install Python, plus dependencies from conda and pip
inputs:
  python-version:
    description: Python version to install. Used as a Conda version constraint.
    required: true

runs:
  using: composite

  steps:
      # Used for the pip cache, not for the python version
    - uses: actions/setup-python@v4
      with:
        cache: 'pip'
        cache-dependency-path: |
          continuous-integration/requirements.txt
          continuous-integration/environment.yaml
          setup.cfg
        python-version: ${{ inputs.python-version }}

    - name: Fetch built emsarray package
      uses: actions/download-artifact@v3
      with:
        name: "Python package"
        path: "dist/"

    - name: Cache conda packages
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{
          hashFiles('continuous-integration/environment.yaml') }}

    - name: Install base Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: continuous-integration/environment.yaml
        python-version: ${{ inputs.python-version }}
        channels: conda-forge
    - shell: bash -l {0}
      run: |
        conda install -c conda-forge wheel


    - name: Install Python packages
      shell: bash -l {0}
      run: |
        pip install \
          -r continuous-integration/requirements.txt \
          dist/emsarray-*.whl
