name: Set up environment
description: Install Python, plus dependencies from conda and pip
inputs:
  python-version:
    description: Python version to install. Used as a Conda version constraint.
    required: true
  package-artifact-name:
    description: Name of the emsarray Python package artifact
    required: false
    default: "Python package"
  dependencies:
    description: Install pinned, latest, or minimum dependency versions.
    required: false
    default: 'pinned'
  extras:
    description: Which set of emsarray extras to install.
    required: false
    default: 'complete'
  groups:
    description: Which set of emsarray dependency groups to install.
    required: false
    default: 'testing'

runs:
  using: composite

  steps:
      # Used for the pip cache, not for the python version
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          continuous-integration/environment.yaml
          pyproject.toml
          poetry.lock

    - name: Fetch built emsarray package
      uses: actions/download-artifact@v8
      with:
        name: ${{ inputs.package-artifact-name }}
        path: "dist/"

    - name: Cache conda packages
      uses: actions/cache@v5
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ hashFiles('continuous-integration/environment.yaml') }}

    - name: Install base Conda environment
      uses: conda-incubator/setup-miniconda@v4
      with:
        environment-file: continuous-integration/environment.yaml
        python-version: ${{ inputs.python-version }}
        miniforge-version: latest
        use-only-tar-bz2: true

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        wheels=( dist/emsarray-*.whl )

        if [[ "${INPUTS_DEPENDENCIES}" == "minimum" ]] ; then
          export POETRY_SOLVER_MIN_RELEASE_AGE=365
          export POETRY_SOLVER_MIN_RELEASE_AGE_EXCLUDE=certify,idna
          # Remove the docs dependency group. It has minimum requirements that
          # do not adhere to the minimum release age solver. This is jank.
          sed -i -e '/^docs = \[$/,/^\]$/{d}' "pyproject.toml"
        fi
        if [[ "${INPUTS_DEPENDENCIES}" != "pinned" ]] ; then
          rm poetry.lock
        fi

        poetry install --no-root --extras="${INPUTS_EXTRAS}" --only="main,${INPUTS_GROUPS}"
        pip install --no-deps "${wheels[0]}"
        pip check

      env:
        INPUTS_DEPENDENCIES: ${{ inputs.dependencies }}
        INPUTS_EXTRAS: ${{ inputs.extras }}
        INPUTS_GROUPS: ${{ inputs.groups }}
