name: Build, test, and lint
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.*"
  pull_request:
    branches:
      - "*"

  workflow_dispatch:

env:
  python-version: "3.14"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.build.outputs.artifact-name }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/build-python-package
        id: build
        with:
          python-version: ${{ env.python-version }}

      - name: "Check py.typed file is included in wheel"
        shell: bash -l {0}
        run: unzip -l dist/*.whl | grep -q py.typed

  build_conda:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: ['build']
    continue-on-error: true

    if: startsWith(github.head_ref, 'release-')

    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          repository: conda-forge/emsarray-feedstock
          path: emsarray-feedstock

      - uses: ./.github/actions/environment
        with:
          python-version: ${{ env.python-version }}
          package-artifact-name: ${{ needs.build.outputs.artifact-name }}

      - run: |
          conda install conda-build
          ./scripts/build-local-conda-package.sh

  test:
    name: python ${{ matrix.python-version }}, ${{ matrix.dependencies }} dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: ["build"]

    # Allow failures for the latest versions
    continue-on-error: ${{ matrix.dependencies == 'latest' }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        dependencies: ["pinned"]
        include:
          - python-version: "3.14"
            dependencies: "latest"
          - python-version: "3.12"
            dependencies: "minimum"


    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/environment
        with:
          python-version: ${{ matrix.python-version }}
          package-artifact-name: ${{ needs.build.outputs.artifact-name }}
          dependencies: ${{ matrix.dependencies }}
          strict: "true"

      - run: |
          echo "MATRIX_TAG=py${MATRIX_PYTHON_VERSION}-${MATRIX_DEPENDENCIES}-deps" >> "$GITHUB_ENV"
        env:
          MATRIX_PYTHON_VERSION: ${{ matrix.python-version }}
          MATRIX_DEPENDENCIES: ${{ matrix.dependencies }}

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -v \
            --mpl \
            --mpl-results-path=./mpl-results \
            --mpl-generate-summary html \
            --junitxml=junit-${MATRIX_TAG}.xml \
            --cov --cov-report term \
            --cov-report xml:coverage-${MATRIX_TAG}.xml

      - name: JUnit report
        uses: mikepenz/action-junit-report@v6
        if: always()
        with:
          report_paths: 'junit-py*.xml'
          check_name: "JUnit test report - ${{ env.MATRIX_TAG }}"
          annotate_only: true
          job_summary: false

      - name: MPL image comparison report
        uses: actions/upload-artifact@v7
        if: ${{ failure() }}
        with:
          name: "MPL image comparison report - python ${{ matrix.python-version }}, ${{ matrix.dependencies }} dependencies"
          path: './mpl-results'
          # No guarantee that the test failures were due to image comparisons
          if-no-files-found: 'ignore'

      - name: Code coverage report
        uses: actions/upload-artifact@v7
        with:
          name: Code coverage for Python ${{ matrix.python-version }}, ${{ matrix.dependencies }} dependencies
          path: coverage-*.xml

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: ["build"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/environment
        with:
          python-version: ${{ env.python-version }}
          package-artifact-name: ${{ needs.build.outputs.artifact-name }}

      - name: 'mypy cache'
        uses: actions/cache@v5
        with:
          path: '.mypy_cache'
          key: mypy-${{ runner.os }}-py${{ env.python-version }}-${{ hashFiles(format('continuous-integration/requirements-{0}.txt', env.python-version)) }}

      - run: flake8 src/ tests/
      - run: isort --diff --check-only src/ tests/
      - run: mypy --junit-xml report-mypy.xml src/

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: ["build"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/environment
        with:
          python-version: ${{ env.python-version }}
          extras: docs
          package-artifact-name: ${{ needs.build.outputs.artifact-name }}

      - name: Set up cartopy cache directories
        id: cartopy
        run: |
          export CARTOPY_DATA_DIR="$RUNNER_TEMP/cartopy"
          echo "CARTOPY_DATA_DIR=$CARTOPY_DATA_DIR" >> $GITHUB_ENV
          python3 -c 'from importlib.metadata import version; v=version("cartopy"); print(f"version={v}\n")' >> $GITHUB_OUTPUT
          python3 -c 'import cartopy; d=cartopy.config["data_dir"]; print(f"data-dir={d}\n")' >> $GITHUB_OUTPUT
          echo "Setting cartopy cache directory to $CARTOPY_DATA_DIR"
        env:
          RUNNER_TEMP: ${{ runner.temp }}

      - name: Restore cartopy cached assets
        uses: actions/cache@v5
        with:
          key: cartopy-data-dir-${{ steps.cartopy.outputs.version }}
          path: ${{ env.CARTOPY_DATA_DIR }}

      - name: Build docs
        run: |
          cd docs/
          sphinx-build -b dirhtml -aEW . _build/dirhtml

      - name: Store compiled docs artifact
        uses: actions/upload-artifact@v7
        with:
          name: Docs
          path: docs/_build/dirhtml

      - name: Copy downloaded cartopy files to cache
        run: |
          if [[ -d "$CARTOPY_CACHE" ]] ; then
            echo "$CARTOPY_CACHE exists, copying to $CARTOPY_DATA_DIR"
            cp -RT "$CARTOPY_CACHE" "$CARTOPY_DATA_DIR"
          fi
        env:
          CARTOPY_CACHE: ${{ steps.cartopy.outputs.data-dir }}
