name: Prerelease checks
on:
  pull_request:
    branches:
      - "release-"

  workflow_dispatch:

env:
  python-version: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-python-package
        with:
          python-version: ${{ env.python-version }}

  build_conda:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: ['build']
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: conda-forge/emsarray-feedstock
          path: emsarray-feedstock

      - uses: ./.github/actions/environment
        with:
          python-version: ${{ env.python-version }}

      - run: |
          conda install conda-build
          ./scripts/build-local-conda-package.sh
